name = "ai-assistant"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[vars]
# Optional vars for local dev defaults (override via secrets in production)
OAUTH_REDIRECT_PATH = "/oauth2/callback"
OPENAI_MODEL = "gpt-4o-mini"

[observability]
enabled = true

[observability.logs]
enabled = true
