name = "ai-assistant-backend"
main = "src/index.ts"
compatibility_date = "2024-10-01"

# Bindings
[[d1_databases]]
binding = "DB"
database_name = "ai_assistant_db"
database_id = "__REPLACE_WITH_D1_ID__"

[vars]
# Optional vars for local dev defaults (override via secrets in production)
OAUTH_REDIRECT_PATH = "/oauth2/callback"
OPENAI_MODEL = "gpt-4o-mini"

[observability]
logs = true
